name: Build OpenWrt

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'false'
    

env:
  REPO_URL: https://github.com/Sagit-chu/scale-build
  REPO_BRANCH: 22.02.3

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo -E apt-get -qq update
        sudo -E apt-get -qq install build-essential debootstrap git python3-pip python3-venv squashfs-tools unzip libjson-perl rsync
        sudo -E apt-get -qq autoremove --purge
        sudo -E apt-get -qq clean
        sudo timedatectl set-timezone "$TZ"
        sudo mkdir -p /workdir
        sudo chown $USER:$GROUPS /workdir
    - name: Clone source code
      working-directory: /workdir
      run: |
        df -hT $PWD
        git clone $REPO_URL -b $REPO_BRANCH scale
        ln -sf /workdir/scale $GITHUB_WORKSPACE/scale

    - name: make clean
      run: |
        cd scale
        sudo make clean

    - name: scale checkout
      run: |
        cd scale
        sudo make checkout

    - name: make packages
      run: |
        cd scale
        sudo make packages
        
    - name: make update
      run: |
        cd scale
        sudo make update

    - name: make iso
      run: |
        cd scale
        sudo make iso

    - name: make clean
      run: |
        cd scale
        sudo make clean

    - name: Organize files
      id: organize
      run: |
        cd scale/tmp/release/*
        echo "FIRMWARE=$PWD" >> $GITHUB_ENV
        echo "::set-output name=status::success"

    - name: Upload firmware to release
      uses: softprops/action-gh-release@v1
      if: steps.organize.outputs.status == 'success' && !cancelled()
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: ${{ env.FIRMWARE }}/*

    - name: Delete workflow runs
      uses: GitRML/delete-workflow-runs@main
      with:
        retain_days: 1
        keep_minimum_runs: 3

    - name: Remove old Releases
      uses: dev-drprasad/delete-older-releases@v0.2.0
      if: env.UPLOAD_RELEASE == 'true' && !cancelled()
      with:
        keep_latest: 3
        delete_tags: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
